### ISSUE TITLE
Very saturated colors are also an accessiblity issue

### ISSUE THREAD

**Issue by simevidas** [components-ai/randoma11y#17]
I can’t find the blog post, but I’ve read somewhere that very saturated colors can be an issue for some people with vision problems. It might be worth making sure that such colors aren’t generated with this tool.

Example:
![capture](https://cloud.githubusercontent.com/assets/716405/15883343/ac6143de-2d47-11e6-80a7-4a1f06a69626.PNG)

**Comment by mrmrs** [comment]
Would like to allow for more config options to generate colors but I don't think we need to limit saturated colors for everyone.
