### ISSUE TITLE
UX Suggestion

### ISSUE THREAD

**Issue by faheempatel** [components-ai/randoma11y#22]
It might just be me but I find that I keep making the error of pasting in the wrong value. I feel it might be better if the colour of the text was the same as the value it represented.

Awesome project btw, I've been using it loads, thanks for making it!

**Comment by lachlanjc** [comment]
@faheempatel Sorry I'm not quite understanding your suggestion :confused:. Where are you pasting in a value?

**Comment by faheempatel** [comment]
@lachlanjc As in, when I paste the hex value from random-a11y into my code I often made the mistake of assuming the value I copied represented the colour of the text and not the background.

![Screenshot describing issue visually](https://cloud.githubusercontent.com/assets/458311/17074941/93c62fc6-507c-11e6-982a-b2c74e306d51.jpg)

**Comment by faheempatel** [comment]
I notice that the CSS is now included on the site and so this becomes less of an issue than it was 👍

**Comment by lachlanjc** [comment]
![FCB31786-4413-4745-8AF1-2C1E7BABFDAE](https://user-images.githubusercontent.com/5074763/103718956-f4c1e000-4f95-11eb-91a9-aa4241344d83.jpeg)
The new design with labels makes this super clear, so closing this :)
