### ISSUE TITLE
Feature request: A user can see the color combo that they voted up

### ISSUE THREAD

**Issue by kellular** [components-ai/randoma11y#36]
Love that users vote up/down and then see new color combinations quickly, however I wish there was a way to:

a. Still be able to view the color combo that I up-voted, rather than the screen switching to the next combo immediately after voting
and/or (this is more of a long-term suggestion)
b. Save all color combos that I up-vote (right now I am just screenshotting ones I like)

**Comment by johnotander** [comment]
Thanks for opening up this issue!

Definitely agree that there should be a way to continue looking at what has just been upvoted. Though, at the same time we'd like to encourage lots of voting. Do you have any ideas on how we can blend showing the most recent up vote while still allowing the ability to vote on a new combination?  cc @mrmrs 

***

The `b` side of this feature is 90% implemented so I hope that it will be ready to roll out sometime this week.

**Comment by lachlanjc** [comment]
@kellular Totally agreed. As of this evening the site gives you CSS for color/background color classes, which you could save (and #38 lets you copy it to your clipboard faster), but that’s still not fabulous.

<img width="1440" alt="screen shot 2016-07-21 at 3 17 02 pm" src="https://cloud.githubusercontent.com/assets/5074763/17035658/9a8818a0-4f56-11e6-8ffa-9b2414b5386a.png">

@johnotander What about saving upvoted combos to localStorage and showing them somewhere in the UI? I don’t think we want the hassle/bulk of authentication and saving them to accounts, and this would be a lightweight solution.

**Comment by johnotander** [comment]
The localStorage part is implemented 😎 . Adam will be working on styling it up when he gets a chance so that we can deploy it.

**Comment by lachlanjc** [comment]
Whoa sweet @johnotander! Can I give it a shot now or is Adam already working on it?

**Comment by johnotander** [comment]
Go for it : )

**Comment by lachlanjc** [comment]
Rad. 🎉

**Comment by lachlanjc** [comment]
Ok. I’m off to bed now but I’ll keep working on this tomorrow!

**Comment by kellular** [comment]
Including the CSS is a great addition. I sometimes got mixed up when I would copy paste hex values like someone else mentioned in #22. I think having the CSS there with color names help a lot!
 
---
I did some quick sketching around "viewing what was just upvoted." Would love some thoughts!

**Concept 1:** Include a "previous" button
- A user can see the previous color combination they voted on, with their choice still selected.

![img_1197](https://cloud.githubusercontent.com/assets/12240896/17067244/8286133c-5010-11e6-92d2-2a8c73469637.JPG)

**Concept 2:** Display previous color combination below current color combo CSS
- A user can see the previous color combination at a glance (maybe just show the color values, rather than color values plus lorem ipsum since "previous color combos" are secondary info)

![img_1199](https://cloud.githubusercontent.com/assets/12240896/17067391/2442e54c-5011-11e6-82f8-c432ed537491.JPG)

**Comment by mrmrs** [comment]
This is really great - I think the whole thing makes sense. One question - if they do go to previous, do we allow them to vote again? I say yes - but interested in others thoughts.

**Comment by lachlanjc** [comment]
I've gotten part of the way through working on a "My Upvotes" section. Here's the basic idea:

![Concept image](https://cloud.githubusercontent.com/assets/5074763/17068656/2f58023c-5020-11e6-8591-be0d310bc382.jpg)

We want to encourage voting as much as possible, and I found that showing every upvoted combo is totally overwhelming and makes you not want to vote and clutter up your screen more. So instead, I'm keeping just a small preview of the upvotes, and using horizontal scrolling so it doesn't grow like crazy.

I'm still fixing a few bugs with this, but you can then hover on a palette and click a button which copies the CSS for that palette to your clipboard.

A few improvements I can think of, but would require state and more complexity:

- A button to clear out your localStorage of votes
- A button to view _all_ your palettes without the horizontal scrolling limits
- A way to "open" a color palette into the big viewer at the top of the screen
- The idea of a _Previous_ button (suggested above) sounds rad 🌟

Thoughts?

**Comment by mrmrs** [comment]
We've removed voting so closing this issue
