### ISSUE TITLE
Replace createClass with ES6 Classes

### ISSUE THREAD

**Issue by lachlanjc** [components-ai/randoma11y#44]

**Comment by samjbmason** [comment]
Anyone working on this?

**Comment by samjbmason** [comment]
I would also be interested in hearing the reasons behind this, purely out of curiosity as to when people decide to change from createClass?

**Comment by lachlanjc** [comment]
@samjbmason A bunch of new React features are only available to ES6 Class components, and [as of Jan 2015 it's the recommended pattern](https://facebook.github.io/react/blog/2015/01/27/react-v0.13.0-beta-1.html#plain-javascript-classes) for React components ([unless they’re stateless](https://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components)). It’s not a priority or a big deal, but it’d be nice to update them sometime.
