### ISSUE TITLE
Add prettier

### ISSUE THREAD

**Issue by skoch** [components-ai/randoma11y#96]
## Proposal
Add an agreed upon prettier configuration to allow for better/easier collaboration. I would also like to add a pre-commit hook to fix things.

### Packages to add
```
prettier
pretty-quick
husky
```

## Reasoning
When attempting to fix a minor issue many lines/fines are changed due to a lack of structure.

https://prettier.io/docs/en/options.html

Seems like `semi` in this repo is ~false~ a mix thus choosing true, everything else would clean things nicely (imho).

```
{
  "semi": true,
  "tabWidth": 2,
  "printWidth": 80,
  "singleQuote": true,
  "arrowParens": "avoid",
  "trailingComma": "all",
  "bracketSpacing": true
}

```

Will happily add this and then can tackle some tech debt (current errors/warnings) and the [latest bug](https://github.com/components-ai/randoma11y/issues/95) regarding the overlap.

Love this project and look forward to contributing.

**Comment by mrmrs** [comment]
@skoch - appreciate this suggestion but generally adding prettier makes it more difficult for me to collaborate so I will pass on this for now.
